name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Private Registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./build
        file: ./build/Dockerfile
        push: true
        tags: ${{ secrets.REGISTRY_URL }}/rustdesk-api-server:latest

    - name: Docker Logout
      run: docker logout ${{ secrets.REGISTRY_URL }}